### ISSUE TITLE
prepi role can't retrieve rootfs?

### ISSUE THREAD

**Issue by elfomze** [smartgic/ansible-playbooks-mycroft#1]
Hi there.

When I try to run the interactive install playbook with my rpi 4B, I hit the following error:
```

TASK [smartgic.prepi : Add pi user gpio, video, audio and render groups] *****************************************************************
ok: [rpi4b01]

TASK [smartgic.prepi : Retrieve rootfs partition UUID] ***********************************************************************************
fatal: [rpi4b01]: FAILED! => {"changed": false, "cmd": ["blkid", "-s", "PARTUUID", "-o", "value", "-t", "LABEL=rootfs"], "delta": "0:00:00.058045", "end": "2022-05-20 14:10:24.507218", "msg": "non-zero return code", "rc": 2, "start": "2022-05-20 14:10:24.449173", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP *******************************************************************************************************************************
rpi4b01                    : ok=10   changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

I am not really sure what causes this, but maybe the issue has to do with the way my pi is partitioned? I am using NOOBS, but I only have rasbian 64bit installed.

Calling blkid straight from the terminal does find my root partition.   

I tried figuring out what happens in the call in tasks/common.yml, but I am a complete ansible newb, so I did not get very far..

I will skip the prepi configuration for now.

**Comment by goldyfruit** [comment]
Hi @elfomze 

So if I understood correctly, the playbook failed but if you run this command as a simple user or as `root` it works, right?
```
blkid -s PARTUUID -o value -t LABEL=rootfs
```

Could you please run the `ansible-playbook` command with `-vvv` and post the output of the task that fails?

**Comment by goldyfruit** [comment]
Invalid.
