### ISSUE TITLE
Failed at "TASK [smartgic.prepi : Reboot the Raspberry Pi and wait for it to restart].

### ISSUE THREAD

**Issue by Chezteeer** [smartgic/ansible-playbooks-mycroft#4]
I was installing using install-interactive.yml, yet I encountered this error. I checked the indicated reboot.yml file and it is indeed missing the eeprom_reboot.

This is the error that I got:

![image](https://user-images.githubusercontent.com/74054662/208819592-ef43e9e3-0ef9-4aec-9e94-1097e1aa07ce.png)

**Comment by Chezteeer** [comment]
Update: I disabled the "prepi_reboot" found in main.yml located at smartgic.prepi default folder. It skipped the process and didn't show the error, I'm worrying that it might be a band-aid fix rather than a proper and complete fix.

**Comment by goldyfruit** [comment]
Hi @Chezteeer,

Did you answer `yes` or `no` to the firmware update question?
```
        ########################################
        # RASPBERRY PI - CONFIG & OPTIMIZATION #
        ########################################

        Do you want to update the firmware and the EEPROM? If you are not sure
        please have a look to the 'prepi' role's README. (yes/no)
```
If `no` has been answered then the `eeprom_reboot` fact from `firmware.yml` is never set which is why you got `eeprom_reboot` is undefined.

I just pushed a commit on https://github.com/smartgic/ansible-role-prep to fix this issuei, could you please retry and see if you get the same issue?

**Comment by Chezteeer** [comment]
Hello @goldyfruit,

The issue was fixed, and my Pi 4 reboot properly. 
Thank you for the quick response!

Going out of the topic, since I'm developing a project through the use of your repository. Is there a way I can contact you directly for questions such as Discord? Thank you again!

**Comment by goldyfruit** [comment]
@Chezteeer awesome!
I'm on Discord https://discord.gg/sHM3Duz5d3
